public class GuessTheNumberGame { // Defines class
    public static void main(String[] args) { // Starts main method (this method, will be executed in program start)
        GuessTheNumberGame game = new GuessTheNumberGame();
        Player player = new HumanPlayer(); // Creates an instance of the HumanPlayer class on variable of type Player named player, because HumanPlayer is a Player´s subclass
        int targetNumber = game.targetNumber();
        System.out.println("¡Welcome, " + player.getName() + "! " + "New random number generated by the game: " + targetNumber); // Welcome message with player´s name obtained to getName() method of the player instance
    }

    private int targetNumber() {
        return (int) (Math.random() * 100) + 1;
    }
}